# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift假面舞会' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift假面舞会

  pod 'Moya/RxSwift', '~> 13.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'IQKeyboardManagerSwift', '~> 6.3.0'



  target 'Swift假面舞会Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift假面舞会UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
